PYTHIA UPDATE: Changing from pythia 8.185 to 8.2
Summary of changes:
- PYTHIA8DATA changed to $PYTHIALOCATION/share/Pythia8/xmldoc
- List of pythia8 libraries changed.
  pythia8 now links to LHAPDF dynamically using 'dl' library.
- Pythia8/Pythia8ToHepMC.h changed to Pythia8Plugins/HepMC2.h
- pythia.statistics() changed to pythia.stat()
- pythia.init() can no longer take parameters

As the result of the last point, all config files
have been updated to include beams (note: for clarity, all other pythia8
configuration options have been moved to .conf files as well)

As a consequence - one parameter from examples/testing/*.cxx programs
became unnecessary and has been removed from Makefiles and .cxx
Comments has been updated to reflect that change.

diff --git a/examples/configure b/examples/configure
--- a/examples/configure
+++ b/examples/configure
@@ -3685,18 +3685,18 @@ fi
 
 
 if test $HAS_PYTHIA = 1; then
-	if test "${ac_cv_header_Pythia8_Pythia8ToHepMC_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for Pythia8/Pythia8ToHepMC.h" >&5
-echo $ECHO_N "checking for Pythia8/Pythia8ToHepMC.h... $ECHO_C" >&6
-if test "${ac_cv_header_Pythia8_Pythia8ToHepMC_h+set}" = set; then
+	if test "${ac_cv_header_Pythia8Plugins_HepMC2_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for Pythia8Plugins/HepMC2.h" >&5
+echo $ECHO_N "checking for Pythia8Plugins/HepMC2.h... $ECHO_C" >&6
+if test "${ac_cv_header_Pythia8Plugins_HepMC2_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_Pythia8_Pythia8ToHepMC_h" >&5
-echo "${ECHO_T}$ac_cv_header_Pythia8_Pythia8ToHepMC_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_Pythia8Plugins_HepMC2_h" >&5
+echo "${ECHO_T}$ac_cv_header_Pythia8Plugins_HepMC2_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking Pythia8/Pythia8ToHepMC.h usability" >&5
-echo $ECHO_N "checking Pythia8/Pythia8ToHepMC.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking Pythia8Plugins/HepMC2.h usability" >&5
+echo $ECHO_N "checking Pythia8Plugins/HepMC2.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3704,7 +3704,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <Pythia8/Pythia8ToHepMC.h>
+#include <Pythia8Plugins/HepMC2.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3740,15 +3740,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking Pythia8/Pythia8ToHepMC.h presence" >&5
-echo $ECHO_N "checking Pythia8/Pythia8ToHepMC.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking Pythia8Plugins/HepMC2.h presence" >&5
+echo $ECHO_N "checking Pythia8Plugins/HepMC2.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <Pythia8/Pythia8ToHepMC.h>
+#include <Pythia8Plugins/HepMC2.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -3782,25 +3782,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: Pythia8/Pythia8ToHepMC.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: Pythia8/Pythia8ToHepMC.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Pythia8Plugins/HepMC2.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: Pythia8Plugins/HepMC2.h: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## -------------------------------------------- ##
@@ -3811,18 +3811,18 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for Pythia8/Pythia8ToHepMC.h" >&5
-echo $ECHO_N "checking for Pythia8/Pythia8ToHepMC.h... $ECHO_C" >&6
-if test "${ac_cv_header_Pythia8_Pythia8ToHepMC_h+set}" = set; then
+echo "$as_me:$LINENO: checking for Pythia8Plugins/HepMC2.h" >&5
+echo $ECHO_N "checking for Pythia8Plugins/HepMC2.h... $ECHO_C" >&6
+if test "${ac_cv_header_Pythia8Plugins_HepMC2_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_Pythia8_Pythia8ToHepMC_h=$ac_header_preproc
+  ac_cv_header_Pythia8Plugins_HepMC2_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_Pythia8_Pythia8ToHepMC_h" >&5
-echo "${ECHO_T}$ac_cv_header_Pythia8_Pythia8ToHepMC_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_Pythia8Plugins_HepMC2_h" >&5
+echo "${ECHO_T}$ac_cv_header_Pythia8Plugins_HepMC2_h" >&6
 
 fi
-if test $ac_cv_header_Pythia8_Pythia8ToHepMC_h = yes; then
+if test $ac_cv_header_Pythia8Plugins_HepMC2_h = yes; then
   :
 else
    HAS_PYTHIA=0 &&
@@ -3836,7 +3836,7 @@ fi
 
 	echo "checking for PYTHIA8DATA: $env_pythia8data"
 	if test $HAS_PYTHIA = 1 && test -z "$env_pythia8data"; then
-		pythia8data=$with_pythia8/xmldoc
+		pythia8data=$with_pythia8/share/Pythia8/xmldoc
 		echo ""
 		echo "WARNING: Pythia8 location is valid, however PYTHIA8DATA"
 		echo "         variable required by Pythia is not set."
